#pragma once

/* Generated with cbindgen:0.27.0 */

/* WARNING: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>


#ifdef __cplusplus
namespace els {
#endif  // __cplusplus

typedef char BufferString[80];

enum Material_Tag
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
  /**
   * Марка
   */
  Steel = 0,
  /**
   * Проценстное содержание олова
   */
  Brass = 1,
};
#ifndef __cplusplus
typedef int32_t Material_Tag;
#endif // __cplusplus

struct Material {
  Material_Tag tag;
  union {
    struct {
      int32_t steel;
    };
    struct {
      float brass;
    };
  };
};

struct FactoryPart {
  BufferString name;
  int32_t count;
  int32_t department_no;
  struct Material material;
  float weight;
  float volume;
};

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

void add_parts(Elasticsearch *handle, const struct FactoryPart *parts, int32_t count);

void close_client(Elasticsearch *handle);

const uint8_t *create_document(Elasticsearch *handle, const char *name);

Elasticsearch *init_client(void);

struct FactoryPart *retrieve_all(Elasticsearch *handle);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#ifdef __cplusplus
}  // namespace els
#endif  // __cplusplus
